#!/usr/bin/env bash
#
# Keyhole installer for Proxmox VE.
#
# Creates an unprivileged Debian 12 container, installs a signed release, and
# leaves you with a URL to set up the first administrator.
#
# Piping a script to a shell is precisely the risk a password manager exists to
# defend against, so: this file pins a release tag rather than main; it verifies
# the binary against a signature made by the key printed below, which you can
# compare against the one in the repository README; and it prints everything it
# is going to do before it does any of it.
#
# The way to run it that lets you check all of that first:
#
#   curl -fsSLO https://raw.githubusercontent.com/ssan9876/keyhole/v1.0.0/scripts/install.sh
#   less install.sh          # read it
#   bash install.sh
#
# --dry-run prints the whole plan and touches nothing. It needs no Proxmox
# host, so you can read the plan on your laptop before running it for real.
set -euo pipefail

OWNER="ssan9876"
REPO="keyhole"
VERSION="v1.0.0"
readonly OWNER REPO VERSION

# The release signing key. Compare it against the README before trusting this
# script — if they differ, stop.
#
# THIS IS A PLACEHOLDER. The keypair is generated by the repository owner with
# `minisign -G`; the secret half becomes the MINISIGN_SECRET_KEY repository
# secret and the public half goes here and in the README. Until it is replaced
# this script refuses to install anything (see check_signing_key), because an
# installer that quietly skips verification is worse than one that does not
# run at all.
readonly MINISIGN_PUBKEY="RWQ...replace-with-the-real-key..."

readonly TEMPLATE_STORAGE="local"
readonly SERVICE_USER="keyhole"
readonly DATA_DIR="/var/lib/keyhole"
readonly CONFIG_DIR="/etc/keyhole"
readonly PORT="8477"

readonly TUNNEL_TOKEN_PATH="${CONFIG_DIR}/tunnel-token"
readonly WORK_DIR="/tmp/keyhole-install"

CTID=""; HOSTNAME_CT="keyhole"; CORES="2"; RAM="1024"; DISK="8"
STORAGE="local-lvm"; BRIDGE="vmbr0"; NETWORK=""; TUNNEL_TOKEN_FILE=""
HOSTNAME_EXTERNAL=""; ADMIN_EMAIL=""; DRY_RUN="no"; ASSUME_YES="no"

# Derived from the above once the flags and prompts have settled.
TUNNEL_TOKEN=""; ADDR=""; BASE_URL=""; BASE_URL_HUMAN=""; HEALTH_URL=""
HEALTH_CURL_FLAGS=""; TEMPLATE=""; TLS_FINGERPRINT=""; ADMIN_OUTPUT=""

die() { printf 'keyhole: %s\n' "$*" >&2; exit 1; }
note() { printf '  %s\n' "$*"; }

# Every side effect goes through run(), which is what makes --dry-run a real plan
# rather than an approximation that drifts from what the script does.
run() {
  if [ "$DRY_RUN" = "yes" ]; then
    printf 'RUN: %s\n' "$*"
    return 0
  fi
  "$@"
}

# For commands that must run inside the container.
in_ct() { run pct exec "$CTID" -- "$@"; }

# Write a file inside the container. The content travels inside the command
# string rather than on a pipe so that it goes through run() like everything
# else — which means --dry-run shows you the exact bytes of every config file
# and unit this script would write. Secrets never come through here; see
# push_tunnel_token.
ct_write() {
  local path="$1" mode="$2" owner="$3" content="$4"
  in_ct sh -c "set -eu
umask 077
cat > '${path}' <<'KEYHOLE_EOF'
${content}
KEYHOLE_EOF
chown '${owner}' '${path}'
chmod '${mode}' '${path}'"
}

# Verification failure must not leave a container that is half-provisioned and
# running: an unverified binary that never got installed is harmless, a running
# container that someone later assumes is a working vault is not.
abort_stopped() {
  printf 'keyhole: %s\n' "$*" >&2
  printf 'keyhole: stopping container %s. Nothing was installed; inspect it with\n' "$CTID" >&2
  printf '         "pct start %s && pct enter %s", or remove it with "pct destroy %s".\n' \
    "$CTID" "$CTID" "$CTID" >&2
  # pct stop loses to a config lock or a concurrent pct operation often enough
  # that swallowing its status is not acceptable here: the three lines above
  # have already told the operator the container is being stopped, and someone
  # who walks away from a running, half-provisioned container believing it is
  # stopped was misled by this script rather than by the failure.
  if ! run pct stop "$CTID"; then
    printf 'keyhole: pct stop %s FAILED — the container is still running; stop it yourself\n' \
      "$CTID" >&2
  fi
  exit 1
}

is_placeholder_key() {
  case "$MINISIGN_PUBKEY" in
    *replace-with-the-real-key*) return 0 ;;
    *) return 1 ;;
  esac
}

# An installer that silently skips verification because nobody filled in the key
# is the worst outcome this file has. Refuse early, and say exactly what to fix.
check_signing_key() {
  if ! is_placeholder_key; then
    return 0
  fi
  if [ "$DRY_RUN" = "yes" ]; then
    return 0
  fi
  die "the release signing key in this script is still a placeholder.
       Replace MINISIGN_PUBKEY near the top of this file with the public key
       published in the ${OWNER}/${REPO} README (one line, beginning \"RW\"),
       then run this again. Without it nothing downloaded can be verified,
       and this script will not install an unverified binary."
}

usage() { cat <<'EOF'
Keyhole installer for Proxmox VE.

Usage: bash install.sh [options]

  --ctid N                  container id                    (default: next free)
  --hostname NAME           container hostname               (default: keyhole)
  --cores N                 CPU cores                        (default: 2)
  --ram MB                  memory in MB                     (default: 1024)
  --disk GB                 root disk in GB                  (default: 8)
  --storage NAME            Proxmox storage for the disk     (default: local-lvm)
  --bridge NAME             network bridge                   (default: vmbr0)
  --network tunnel|tls|proxy  how the vault is reached       (default: prompt)
  --tunnel-token-file PATH  read the Cloudflare token from a file
                            (tunnel mode; otherwise prompted for, never echoed)
  --hostname-external NAME  the public hostname, for base_url
                            (required by tunnel and proxy modes)
  --admin-email ADDR        the first administrator          (default: prompt)
  --dry-run                 print every command that would run, change nothing
  --yes                     skip the confirmation
  -h, --help                this text

The three network modes:

  tunnel  binds 127.0.0.1:8477; Cloudflare terminates TLS; installs cloudflared
          and registers it from a token file that is never passed as an argument
  tls     binds 0.0.0.0:8477 and terminates TLS itself with a self-signed
          certificate generated here; prints the certificate's SHA-256
          fingerprint so the browser warning can be checked against something
  proxy   binds 127.0.0.1:8477 and terminates no TLS; your reverse proxy does

There is no plain-HTTP mode. SubtleCrypto is exposed only in a secure context,
so on a plain http:// origin that is not localhost window.crypto.subtle is
undefined and every AES-GCM call in the web app throws. That is not a degraded
install — it is a vault that cannot open a single item.
EOF
}

parse_args() {
  while [ $# -gt 0 ]; do
    case "$1" in
      --ctid) [ $# -ge 2 ] || die "--ctid needs a value"; CTID="$2"; shift 2 ;;
      --hostname) [ $# -ge 2 ] || die "--hostname needs a value"; HOSTNAME_CT="$2"; shift 2 ;;
      --cores) [ $# -ge 2 ] || die "--cores needs a value"; CORES="$2"; shift 2 ;;
      --ram) [ $# -ge 2 ] || die "--ram needs a value"; RAM="$2"; shift 2 ;;
      --disk) [ $# -ge 2 ] || die "--disk needs a value"; DISK="$2"; shift 2 ;;
      --storage) [ $# -ge 2 ] || die "--storage needs a value"; STORAGE="$2"; shift 2 ;;
      --bridge) [ $# -ge 2 ] || die "--bridge needs a value"; BRIDGE="$2"; shift 2 ;;
      --network) [ $# -ge 2 ] || die "--network needs a value"; NETWORK="$2"; shift 2 ;;
      --tunnel-token-file) [ $# -ge 2 ] || die "--tunnel-token-file needs a value"; TUNNEL_TOKEN_FILE="$2"; shift 2 ;;
      --hostname-external) [ $# -ge 2 ] || die "--hostname-external needs a value"; HOSTNAME_EXTERNAL="$2"; shift 2 ;;
      --admin-email) [ $# -ge 2 ] || die "--admin-email needs a value"; ADMIN_EMAIL="$2"; shift 2 ;;
      --dry-run) DRY_RUN="yes"; shift ;;
      --yes) ASSUME_YES="yes"; shift ;;
      -h|--help) usage; exit 0 ;;
      # An unknown flag stops. Ignoring it would silently drop an option the
      # operator believes they set — --network among them.
      *) die "unknown option: $1" ;;
    esac
  done
}

require_pve() {
  if [ "$DRY_RUN" = "yes" ]; then
    return 0
  fi
  command -v pveversion >/dev/null 2>&1 || die "this must run on a Proxmox VE host"
  [ "$(id -u)" -eq 0 ] || die "this must run as root"
}

prompt_network() {
  cat <<'EOF'

How will this vault be reached?

  1) tunnel   Cloudflare Tunnel. Nothing is exposed on your router; Cloudflare
              terminates TLS. Needs a tunnel token from the Zero Trust
              dashboard.
  2) tls      LAN only, on the container's own address, with a self-signed
              certificate generated here. The browser warns once; the
              fingerprint is printed so you can check it.
  3) proxy    You already have a reverse proxy terminating TLS. This writes no
              certificates and binds loopback only.

There is no plain-HTTP option: window.crypto.subtle does not exist outside a
secure context, so an http:// origin gives you a vault that cannot decrypt a
single item.

EOF
  local choice
  printf 'Choose [1-3]: '
  read -r choice || die "aborted"
  case "$choice" in
    1|tunnel) NETWORK="tunnel" ;;
    2|tls) NETWORK="tls" ;;
    3|proxy) NETWORK="proxy" ;;
    *) die "not one of 1, 2 or 3: $choice" ;;
  esac
}

prompt_for_missing() {
  if [ -z "$NETWORK" ]; then
    prompt_network
  fi
  case "$NETWORK" in
    tunnel|tls|proxy) ;;
    *) die "--network must be one of tunnel, tls or proxy (got: $NETWORK)" ;;
  esac

  if [ "$NETWORK" != "tls" ] && [ -z "$HOSTNAME_EXTERNAL" ]; then
    printf '\nPublic hostname the vault will be reached at (for example vault.example.com): '
    read -r HOSTNAME_EXTERNAL || die "aborted"
    [ -n "$HOSTNAME_EXTERNAL" ] || die "--hostname-external is required in ${NETWORK} mode"
  fi
  if [ "$NETWORK" = "tls" ] && [ -n "$HOSTNAME_EXTERNAL" ]; then
    die "--hostname-external does not apply to tls mode: base_url is the container's own address"
  fi

  if [ -z "$ADMIN_EMAIL" ]; then
    printf '\nEmail address of the first administrator: '
    read -r ADMIN_EMAIL || die "aborted"
    [ -n "$ADMIN_EMAIL" ] || die "--admin-email is required"
  fi
}

# The token is read here, before anything is created, so a typo in the path
# fails on a host with no container on it. It is never echoed, never passed as
# an argument, and never printed by the plan.
read_tunnel_token() {
  if [ "$NETWORK" != "tunnel" ]; then
    return 0
  fi
  if [ -n "$TUNNEL_TOKEN_FILE" ]; then
    [ -r "$TUNNEL_TOKEN_FILE" ] || die "cannot read the tunnel token file: $TUNNEL_TOKEN_FILE"
    TUNNEL_TOKEN="$(tr -d '\r\n' < "$TUNNEL_TOKEN_FILE")"
  else
    printf '\nCloudflare tunnel token (not echoed): ' >&2
    IFS= read -rs TUNNEL_TOKEN || die "aborted"
    printf '\n' >&2
  fi
  # A dry run reads whatever it was pointed at and asserts nothing about it —
  # /dev/null is a legitimate thing to point a dry run at, and refusing it would
  # mean the plan could only be produced by someone who already holds the token.
  if [ "$DRY_RUN" != "yes" ] && [ -z "$TUNNEL_TOKEN" ]; then
    die "the tunnel token is empty"
  fi
}

# Turns the answers into the three values that differ between modes: what the
# server binds, what origin it believes it is served from, and where this script
# looks for /healthz afterwards.
resolve_settings() {
  case "$NETWORK" in
    tunnel)
      ADDR="127.0.0.1:${PORT}"
      BASE_URL="https://${HOSTNAME_EXTERNAL}"
      BASE_URL_HUMAN="$BASE_URL"
      HEALTH_URL="http://127.0.0.1:${PORT}/healthz"
      HEALTH_CURL_FLAGS="-fsS"
      ;;
    tls)
      ADDR="0.0.0.0:${PORT}"
      # Not known until the container is up and DHCP has answered, so the config
      # file is written by a command that resolves it inside the container.
      BASE_URL=""
      BASE_URL_HUMAN="https://<the container's address>:${PORT}"
      HEALTH_URL="https://127.0.0.1:${PORT}/healthz"
      # -k, because the certificate this very script just generated is
      # self-signed and there is nothing here that could trust it.
      HEALTH_CURL_FLAGS="-fsSk"
      ;;
    proxy)
      ADDR="127.0.0.1:${PORT}"
      BASE_URL="https://${HOSTNAME_EXTERNAL}"
      BASE_URL_HUMAN="$BASE_URL"
      HEALTH_URL="http://127.0.0.1:${PORT}/healthz"
      HEALTH_CURL_FLAGS="-fsS"
      ;;
  esac
}

resolve_ctid() {
  if [ -n "$CTID" ]; then
    return 0
  fi
  if [ "$DRY_RUN" = "yes" ]; then
    printf 'RUN: pvesh get /cluster/nextid\n'
    CTID="<next free container id>"
    return 0
  fi
  CTID="$(pvesh get /cluster/nextid)"
  [ -n "$CTID" ] || die "pvesh get /cluster/nextid returned nothing"
}

print_plan() {
  cat <<EOF

Keyhole ${VERSION} will be installed as follows.

  Container    ${CTID} (${HOSTNAME_CT}), unprivileged Debian 12
  Resources    ${CORES} cores, ${RAM} MB RAM, ${DISK} GB on ${STORAGE}, bridge ${BRIDGE}
  Reached by   ${NETWORK}
  Reached at   ${BASE_URL_HUMAN}
  Binary       https://github.com/${OWNER}/${REPO}/releases/download/${VERSION}/keyhole-linux-\${arch}
               verified against SHA256SUMS and its minisign signature
  Data         ${DATA_DIR} (SQLite; entirely ciphertext)
  Config       ${CONFIG_DIR}/config.yml
  Service      systemd unit "keyhole", running as ${SERVICE_USER}
  Admin        ${ADMIN_EMAIL}

Nothing has been changed yet.
EOF
  if is_placeholder_key; then
    cat <<'EOF'

!! The release signing key in this copy of the script is still a placeholder,
!! so it can verify nothing. A real install refuses to start until
!! MINISIGN_PUBKEY is replaced with the key published in the README.
EOF
  fi
  if [ "$ASSUME_YES" = "yes" ]; then
    return 0
  fi
  printf '\nProceed? [y/N] '
  local answer
  read -r answer || die "aborted"
  case "$answer" in y|Y|yes) ;; *) die "aborted" ;; esac
}

# Do not hard-code a template filename: the Debian point release moves, and a
# pinned name turns into a 404 on a schedule nobody here controls.
ensure_template() {
  run pveam update
  local -a pick=(sh -c "pveam available --section system | awk '{print \$2}' | grep '^debian-12-standard' | sort -V | tail -n 1")
  if [ "$DRY_RUN" = "yes" ]; then
    printf 'RUN: %s\n' "${pick[*]}"
    note "the newest debian-12-standard in that list is the template; it is downloaded if absent"
    TEMPLATE="${TEMPLATE_STORAGE}:vztmpl/<newest debian-12-standard>"
    run pveam download "$TEMPLATE_STORAGE" "<newest debian-12-standard>"
    return 0
  fi
  local newest
  newest="$("${pick[@]}")"
  [ -n "$newest" ] || die "pveam available --section system offered no debian-12-standard template"
  # -F: the filename carries the point release, so it is full of dots, and as a
  # regex those match anything. A fixed-string compare is what "is this exact
  # template already here" actually means.
  if ! pveam list "$TEMPLATE_STORAGE" | grep -qF "vztmpl/${newest}"; then
    run pveam download "$TEMPLATE_STORAGE" "$newest"
  fi
  TEMPLATE="${TEMPLATE_STORAGE}:vztmpl/${newest}"
}

create_container() {
  run pct create "$CTID" "$TEMPLATE" \
    --hostname "$HOSTNAME_CT" \
    --cores "$CORES" \
    --memory "$RAM" \
    --swap 0 \
    --rootfs "${STORAGE}:${DISK}" \
    --net0 "name=eth0,bridge=${BRIDGE},ip=dhcp" \
    --unprivileged 1 \
    --features nesting=0 \
    --onboot 1
  run pct start "$CTID"
  # pct start returns as soon as the container is created, not as soon as it can
  # run anything; without this every command below races init.
  if ! run sh -c "i=0; while [ \$i -lt 60 ]; do pct exec ${CTID} -- true >/dev/null 2>&1 && exit 0; i=\$((i+1)); sleep 1; done; exit 1"; then
    die "container ${CTID} started but never became reachable with pct exec"
  fi
}

provision_base() {
  local packages="ca-certificates curl minisign"
  case "$NETWORK" in
    tls) packages="${packages} openssl" ;;
    tunnel) packages="${packages} gnupg" ;;
  esac
  in_ct sh -c "set -eu
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y --no-install-recommends ${packages}"
}

install_binary() {
  local base="https://github.com/${OWNER}/${REPO}/releases/download/${VERSION}"

  if ! in_ct sh -c "set -eu
rm -rf '${WORK_DIR}'
mkdir -p '${WORK_DIR}'
cd '${WORK_DIR}'
arch=\$(dpkg --print-architecture)
curl -fsSL --proto '=https' --tlsv1.2 -o \"keyhole-linux-\$arch\" \"${base}/keyhole-linux-\$arch\"
curl -fsSL --proto '=https' --tlsv1.2 -o SHA256SUMS \"${base}/SHA256SUMS\"
curl -fsSL --proto '=https' --tlsv1.2 -o SHA256SUMS.minisig \"${base}/SHA256SUMS.minisig\""; then
    abort_stopped "downloading ${VERSION} failed"
  fi

  # The signature first. It is what makes the checksum list mean anything: a
  # SHA256SUMS that arrived over the same connection as the binary proves only
  # that the two agree with each other.
  if ! in_ct sh -c "set -eu
cd '${WORK_DIR}'
minisign -Vm SHA256SUMS -P '${MINISIGN_PUBKEY}'"; then
    abort_stopped "the minisign signature over SHA256SUMS did not verify against the key in this script"
  fi

  # Then the checksum, which is now a statement signed by the release key.
  # --ignore-missing because SHA256SUMS lists both architectures and only one
  # of them was downloaded.
  if ! in_ct sh -c "set -eu
cd '${WORK_DIR}'
sha256sum -c SHA256SUMS --ignore-missing"; then
    abort_stopped "the downloaded binary does not match its signed checksum"
  fi

  # Only now does anything reach an executable path.
  in_ct sh -c "set -eu
cd '${WORK_DIR}'
arch=\$(dpkg --print-architecture)
install -o root -g root -m 0755 \"keyhole-linux-\$arch\" /usr/local/bin/keyhole
rm -rf '${WORK_DIR}'"

  # The update shim, so the command the closing message names is the command
  # that exists. `keyhole update` re-runs this same verification against the
  # latest release and rolls back a binary that will not answer /healthz.
  ct_write /usr/local/bin/update 0755 root:root "#!/bin/sh
exec /usr/local/bin/keyhole update \"\$@\""
}

create_service_user() {
  in_ct sh -c "set -eu
id -u '${SERVICE_USER}' >/dev/null 2>&1 || useradd --system --home-dir '${DATA_DIR}' --shell /usr/sbin/nologin '${SERVICE_USER}'"
  # 0700: the database is entirely ciphertext, but the server secret next to it
  # is not, and nothing but the service has any business in this directory.
  in_ct install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0700 "$DATA_DIR"
  in_ct install -d -o root -g root -m 0755 "$CONFIG_DIR"
}

# The one side effect that deliberately does not go through run(): the token has
# to reach the container on a pipe, and run() cannot carry stdin. A dry run
# prints a redacted line instead. The whole point of the file is that the secret
# never appears in an argument list, a process table, a shell history or a plan.
push_tunnel_token() {
  if [ "$DRY_RUN" = "yes" ]; then
    printf 'RUN: pct exec %s -- sh -c "umask 077; cat > %s"  < the tunnel token (not shown)\n' \
      "$CTID" "$TUNNEL_TOKEN_PATH"
    printf 'RUN: pct exec %s -- chown root:root %s\n' "$CTID" "$TUNNEL_TOKEN_PATH"
    printf 'RUN: pct exec %s -- chmod 0600 %s\n' "$CTID" "$TUNNEL_TOKEN_PATH"
    return 0
  fi
  printf '%s' "$TUNNEL_TOKEN" | pct exec "$CTID" -- sh -c "umask 077; cat > '${TUNNEL_TOKEN_PATH}'"
  pct exec "$CTID" -- chown root:root "$TUNNEL_TOKEN_PATH"
  pct exec "$CTID" -- chmod 0600 "$TUNNEL_TOKEN_PATH"
}

configure_network() {
  case "$NETWORK" in
    tunnel)
      in_ct sh -c "set -eu
install -d -m 0755 /usr/share/keyrings
curl -fsSL --proto '=https' --tlsv1.2 https://pkg.cloudflare.com/cloudflare-main.gpg -o /usr/share/keyrings/cloudflare-main.gpg
chmod 0644 /usr/share/keyrings/cloudflare-main.gpg
echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared bookworm main' > /etc/apt/sources.list.d/cloudflared.list
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y --no-install-recommends cloudflared"
      push_tunnel_token
      # The token is exported from the file rather than given as an argument.
      # Arguments are readable by every process on the box through /proc and
      # land in the shell history of whoever typed them.
      in_ct sh -c "set -eu
TUNNEL_TOKEN=\$(cat '${TUNNEL_TOKEN_PATH}')
export TUNNEL_TOKEN
cloudflared service install
systemctl enable --now cloudflared"
      ;;
    tls)
      # -addext subjectAltName is not optional decoration: a certificate with
      # the address only in CN is rejected outright by every current browser,
      # and "rejected" here means no secure context and no crypto.subtle.
      in_ct sh -c "set -eu
ip=\$(hostname -I | cut -d' ' -f1)
[ -n \"\$ip\" ] || { echo 'the container has no IPv4 address yet' >&2; exit 1; }
umask 077
openssl req -x509 -newkey rsa:2048 -nodes -days 3650 -subj \"/CN=\$ip\" -addext \"subjectAltName=IP:\$ip\" -keyout '${CONFIG_DIR}/tls.key' -out '${CONFIG_DIR}/tls.crt'
chown root:${SERVICE_USER} '${CONFIG_DIR}/tls.key' '${CONFIG_DIR}/tls.crt'
chmod 0640 '${CONFIG_DIR}/tls.key' '${CONFIG_DIR}/tls.crt'"
      local -a fingerprint=(pct exec "$CTID" -- openssl x509 -noout -fingerprint -sha256 -in "${CONFIG_DIR}/tls.crt")
      if [ "$DRY_RUN" = "yes" ]; then
        printf 'RUN: %s\n' "${fingerprint[*]}"
        TLS_FINGERPRINT="(read from the certificate once it has been generated)"
      else
        TLS_FINGERPRINT="$("${fingerprint[@]}")" || die "could not read the certificate fingerprint"
      fi
      ;;
    proxy)
      note "proxy mode writes no TLS material; your reverse proxy holds the certificate"
      ;;
  esac
}

write_config() {
  case "$NETWORK" in
    tunnel|proxy)
      ct_write "${CONFIG_DIR}/config.yml" 0640 "root:${SERVICE_USER}" "# Written by scripts/install.sh (Keyhole ${VERSION}).
addr: ${ADDR}
data_dir: ${DATA_DIR}
base_url: ${BASE_URL}
log_level: info"
      ;;
    tls)
      # base_url has to name the container's own address, which DHCP does not
      # decide until the container is up — so the file is written by a command
      # that resolves it in the container rather than by this script guessing.
      in_ct sh -c "set -eu
ip=\$(hostname -I | cut -d' ' -f1)
# An empty \$ip here would write \"base_url: https://:8477\" and produce a vault
# whose setup links point nowhere, with nothing to say why. configure_network
# already fails on this, so reaching it means the two were reordered.
[ -n \"\$ip\" ] || { echo 'the container has no IPv4 address yet' >&2; exit 1; }
umask 077
cat > '${CONFIG_DIR}/config.yml' <<EOF
# Written by scripts/install.sh (Keyhole ${VERSION}).
addr: ${ADDR}
data_dir: ${DATA_DIR}
base_url: https://\$ip:${PORT}
log_level: info
tls_cert: ${CONFIG_DIR}/tls.crt
tls_key: ${CONFIG_DIR}/tls.key
EOF
chown 'root:${SERVICE_USER}' '${CONFIG_DIR}/config.yml'
chmod 0640 '${CONFIG_DIR}/config.yml'"
      ;;
  esac
}

write_unit() {
  ct_write /etc/systemd/system/keyhole.service 0644 root:root "[Unit]
Description=Keyhole password manager
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_USER}
ExecStart=/usr/local/bin/keyhole serve --config ${CONFIG_DIR}/config.yml
Restart=on-failure
RestartSec=2

# The process needs one writable directory and nothing else. Everything below
# is what keeps a compromise of the HTTP handler from becoming a compromise of
# the container.
NoNewPrivileges=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectSystem=strict
ProtectHome=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictSUIDSGID=yes
RestrictNamespaces=yes
LockPersonality=yes
# Safe here, and worth keeping: the binary is CGO_ENABLED=0 static Go with no
# JIT and no plugins, so nothing it does needs a page that is both writable and
# executable. If something later appears to break under it, that is a reason to
# find out what is allocating W+X memory, not a reason to delete this line.
MemoryDenyWriteExecute=yes
SystemCallFilter=@system-service
SystemCallArchitectures=native
ReadWritePaths=${DATA_DIR}

[Install]
WantedBy=multi-user.target"
  in_ct systemctl daemon-reload
}

bootstrap_admin() {
  # Migrate as root before the service ever runs, so the first thing the
  # unprivileged unit does is not a schema change.
  in_ct keyhole migrate --config "${CONFIG_DIR}/config.yml"
  in_ct chown -R "${SERVICE_USER}:${SERVICE_USER}" "$DATA_DIR"
  in_ct systemctl enable --now keyhole

  if ! run sh -c "i=0; while [ \$i -lt 30 ]; do pct exec ${CTID} -- curl ${HEALTH_CURL_FLAGS} -o /dev/null '${HEALTH_URL}' >/dev/null 2>&1 && exit 0; i=\$((i+1)); sleep 1; done; exit 1"; then
    die "keyhole started but never answered ${HEALTH_URL}; check \"pct exec ${CTID} -- journalctl -u keyhole\""
  fi

  # Captured rather than run through run(), because the setup link is the whole
  # point of this step and it only exists in this command's output. The dry-run
  # branch prints the identical command line, so the plan stays complete.
  local -a create=(pct exec "$CTID" -- runuser -u "$SERVICE_USER" -- \
    keyhole admin create --email "$ADMIN_EMAIL" --config "${CONFIG_DIR}/config.yml")
  if [ "$DRY_RUN" = "yes" ]; then
    printf 'RUN: %s\n' "${create[*]}"
    return 0
  fi
  ADMIN_OUTPUT="$("${create[@]}")" || die "creating the first administrator failed"
}

print_next_steps() {
  # A dry run must not close by announcing an install that did not happen.
  if [ "$DRY_RUN" = "yes" ]; then
    printf '\n%s\n' "That is the entire plan for Keyhole ${VERSION} in container ${CTID}. Nothing was changed."
    printf '%s\n' "The setup link is printed by \"keyhole admin create\" at the end of a real run."
  else
    printf '\n%s\n' "Keyhole ${VERSION} is installed in container ${CTID}."
    printf '%s\n' "$ADMIN_OUTPUT"
  fi
  printf '\n'

  case "$NETWORK" in
    tls)
      cat <<EOF
The certificate is self-signed, so the browser warns the first time. Check the
fingerprint it shows you against this one rather than clicking through:

  ${TLS_FINGERPRINT}

EOF
      ;;
    proxy)
      cat <<EOF
Two things your reverse proxy needs:

  proxy_pass    http://<this container's address>:${PORT}
  it must serve ${BASE_URL} over TLS — a secure context, or the web app has no
  window.crypto.subtle and cannot decrypt anything

EOF
      ;;
    tunnel)
      cat <<EOF
The tunnel is registered. Point the Cloudflare public hostname
${HOSTNAME_EXTERNAL} at http://localhost:${PORT} in the Zero Trust dashboard if
you have not already.

EOF
      ;;
  esac

  cat <<EOF
Worth knowing:

  Data          ${DATA_DIR} inside container ${CTID} — item bodies, names and
                URLs are ciphertext the server has never held a key for
  Back up       pct exec ${CTID} -- keyhole backup
                (a snapshot is entirely ciphertext, so copying it somewhere
                less trusted than this host is a reasonable thing to do)
  Update        pct exec ${CTID} -- update
                (verifies the signature the same way this install did, and
                rolls back if the new binary will not answer /healthz)
  Logs          pct exec ${CTID} -- journalctl -u keyhole -f
EOF
}

main() {
  parse_args "$@"
  # Before require_pve, deliberately. This one is about what is in this file
  # rather than what is on this host, so the operator should hear about it
  # wherever they are reading the script — not only once they are root on a
  # Proxmox node.
  check_signing_key
  require_pve
  prompt_for_missing
  read_tunnel_token
  resolve_settings
  resolve_ctid
  print_plan

  ensure_template
  create_container
  provision_base
  install_binary
  create_service_user
  configure_network
  write_config
  write_unit
  bootstrap_admin
  print_next_steps
}

main "$@"
